spring:
  application:
    name: appraisal-service
  config:
    import: optional:configserver:optional:configserver:http://appraisal-config-server-app-0.appraisal-config-server-app.default.svc.cluster.local:8888