server:
  port: 9009
spring:
  jpa:
    properties.hibernate.dialect : org.hibernate.dialect.PostgreSQLDialect
    hibernate.show-sql: true
    hibernate.ddl-auto: validate
  datasource:
    url: ${URL}
    username: ${USERNAME}
    password: ${PASSWORD}
    initialize: true
  flyway:
    enabled: true
  sql:
    init:
      continue-on-error: false
      mode: always

