apiVersion: apps/v1
kind: Deployment
metadata:
  name: appraisal-backend-app
spec:
  selector:
    matchLabels:
      app: appraisal-backend-app
  replicas: 1
  template:
    metadata:
      labels:
        app: appraisal-backend-app
    spec:
      containers:
        - name: appraisal-backend-app
          image: lolalambe/appraisal-backend-service:0.0.1-SNAPSHOT
          imagePullPolicy: Always
          ports:
            - containerPort: 9009