CREATE TABLE IF NOT EXISTS employee_managers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    employee_id BIGINT NOT NULL,
    manager_id BIGINT NOT NULL,
    deleted BOOLEAN DEFAULT FALSE,
    created_on TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_modified_on TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_employee_manager PRIMARY KEY (id),
    CONSTRAINT FK_employee_manager_employee_id FOREIGN KEY (employee_id) REFERENCES employees(id),
    CONSTRAINT FK_employee_manager_manager_id FOREIGN KEY (manager_id) REFERENCES managers(id)
);