CREATE TABLE IF NOT EXISTS employee_teams (
    id  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    team_id BIGINT NOT NULL,
    employee_id BIGINT NOT NULL,
    deleted BOOLEAN DEFAULT FALSE ,
    created_on TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_modified_on TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_employee_team PRIMARY KEY (id),
    CONSTRAINT FK_employee_teams_employee_id FOREIGN KEY (employee_id) REFERENCES employees(id),
    CONSTRAINT FK_employee_teams_team_id FOREIGN KEY (team_id) REFERENCES teams(id)
);