CREATE TABLE IF NOT EXISTS feedback_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    request_type VARCHAR(50) NOT NULL,
    requester_id BIGINT NOT NULL,
    actor_id BIGINT NOT NULL,
    employee_id BIGINT NOT NULL,
    request_status VARCHAR(50) NOT NULL,
    expiry TIMESTAMP NULL,
    deleted BOOLEAN DEFAULT FALSE ,
    created_on TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_modified_on TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_feedback_request PRIMARY KEY (id),
    CONSTRAINT FK_feedback_request_requester FOREIGN KEY (requester_id) REFERENCES users(id),
    CONSTRAINT FK_feedback_request_actor FOREIGN KEY (actor_id) REFERENCES employees(id),
    CONSTRAINT FK_feedback_request_employee FOREIGN KEY (employee_id) REFERENCES employees(id)
);