CREATE TABLE IF NOT EXISTS feedback_request_entry (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    feedback_request_id BIGINT NOT NULL,
    question_id BIGINT NOT NULL,
    answer TEXT NOT NULL,
    deleted BOOLEAN DEFAULT FALSE ,
    created_on TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_modified_on TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_feedback_request_entry PRIMARY KEY (id),
    CONSTRAINT FK_request_entry_request FOREIGN KEY (feedback_request_id) REFERENCES feedback_requests(id),
    CONSTRAINT FK_request_entry_question FOREIGN KEY (question_id) REFERENCES questions(id)
);